name = "oliviuus"
compatibility_date = "2025-11-04"
pages_build_output_dir = "./dist"

[env.production]
pages_build_output_dir = "./dist"

# GitHub deployment configuration
[deployment]
environment = "production"
trigger_branch = "main"